import type { Metadata } from "next";
import { ScrollProvider } from "@/context/useScroll";
import {
  Inter,
  Poppins,
  Mouse_Memoirs,
  Mochiy_Pop_One,
  Monda,
} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});
const mouse = Mouse_Memoirs({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mouse",
});

const mochiy = Mochiy_Pop_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mochiy",
});

const monda = Monda({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-monda",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ScrollProvider>
      <html lang="en">
        <body
          className={`${inter.className} ${mochiy.variable} ${mouse.variable} ${poppins.variable} ${monda.variable}`}
        >
          <main>
            <Header />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </ScrollProvider>
  );
}
